"use client";

import Link from "next/link";
import { useEffect } from "react";

import { Button } from "@/components/ui/button";

/**
 * Error boundary for any throw inside the `(app)` segment. Replaces the default white screen
 * with a friendly message + reset + "go home" link.
 *
 * Do not edit this file — it ships as the production-quality default. To override per feature,
 * add `src/app/(app)/<feature>/error.tsx` instead.
 *
 * Note: `error.tsx` is intentionally NOT shown for `notFound()` (Next handles those via
 * `not-found.tsx`) and not shown for thrown redirects.
 */
export default function AppSegmentError({
  error,
  reset,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    console.error("[(app) error boundary]", error);
  }, [error]);

  return (
    <div className="mx-auto flex max-w-md flex-col items-center justify-center gap-4 py-16 text-center">
      <h1 className="text-2xl font-semibold tracking-tight">Something went wrong</h1>
      <p className="text-sm text-muted-foreground">
        We hit an unexpected error rendering this page. You can try again or head back home.
      </p>
      {error.digest ? (
        <p className="text-xs text-muted-foreground/70">Reference: {error.digest}</p>
      ) : null}
      <div className="flex flex-wrap items-center justify-center gap-2">
        <Button type="button" onClick={() => reset()}>
          Try again
        </Button>
        <Button type="button" variant="outline" render={<Link href="/home" />}>
          Back to Home
        </Button>
      </div>
    </div>
  );
}
