import { Skeleton } from "@/components/ui/skeleton";

/**
 * Default loading skeleton shown while any `(app)` route segment is server-rendering.
 * Generated MVPs may override this per sub-segment by adding their own `loading.tsx`.
 *
 * Do not edit this file — it ships as the production-quality default. To override visuals
 * for a specific feature, add `src/app/(app)/<feature>/loading.tsx` instead.
 */
export default function AppSegmentLoading() {
  return (
    <div className="space-y-4 p-2" aria-busy="true" aria-live="polite">
      <Skeleton className="h-8 w-1/3" />
      <Skeleton className="h-4 w-1/2" />
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">
        <Skeleton className="h-32" />
        <Skeleton className="h-32" />
        <Skeleton className="h-32" />
      </div>
    </div>
  );
}
