import Link from "next/link";

import { Button } from "@/components/ui/button";

/**
 * 404 boundary for any unmatched route inside `(app)`. Use a friendly message + a way back
 * instead of the default Next.js fallback.
 *
 * Do not edit this file — it ships as the production-quality default. To override per feature,
 * add `src/app/(app)/<feature>/not-found.tsx` instead.
 */
export default function AppSegmentNotFound() {
  return (
    <div className="mx-auto flex max-w-md flex-col items-center justify-center gap-4 py-16 text-center">
      <h1 className="text-2xl font-semibold tracking-tight">Page not found</h1>
      <p className="text-sm text-muted-foreground">
        We couldn&apos;t find the page you were looking for. It may have moved or been removed.
      </p>
      <Button type="button" render={<Link href="/home" />}>
        Back to Home
      </Button>
    </div>
  );
}
