import { NextRequest, NextResponse } from "next/server";

import { getSessionCookie } from "better-auth/cookies";

/**
 * Edge middleware — runs before every matched request.
 *
 * Responsibilities:
 *   1. **Auth gate**: redirect unauthenticated users to `/login` for `(app)` routes. We use
 *      `getSessionCookie(request)` (Better Auth's edge-safe helper) so the check is fast and
 *      doesn't hit the database. The `(app)/layout.tsx` still does a full session check on the
 *      server — this is defense-in-depth that catches the unauthenticated case earlier.
 *   2. **Security headers**: send a baseline CSP / HSTS / referrer-policy on every response.
 *   3. **In-memory rate limiting**: 60 req/min per IP for `/api/**` (excluding auth). For
 *      production scale, swap to Upstash Redis — interface stays the same.
 *
 * `E2E_BYPASS_AUTH=true` skips the auth redirect (matches `(app)/layout.tsx` behavior).
 *
 * Do not edit this file.
 */
const RATE_LIMIT_WINDOW_MS = 60_000;
const RATE_LIMIT_MAX = 60;
const RATE_LIMIT_PATHS = /^\/api\//;
const RATE_LIMIT_EXEMPT = /^\/api\/auth\//;
const APP_PATHS = /^\/(home|settings)(\/|$)/;
const SHARE_PATHS = /^\/share(\/|$)/;
const PUBLIC_API = /^\/api\/auth(\/|$)/;

type RateBucket = { hits: number; resetAt: number };
const ipBuckets = new Map<string, RateBucket>();

function getClientIp(request: NextRequest): string {
  const forwarded = request.headers.get("x-forwarded-for");
  if (forwarded) return forwarded.split(",")[0]!.trim();
  const realIp = request.headers.get("x-real-ip");
  if (realIp) return realIp.trim();
  return "unknown";
}

function checkRateLimit(ip: string): { allowed: boolean; resetAt: number } {
  const now = Date.now();
  const bucket = ipBuckets.get(ip);
  if (!bucket || bucket.resetAt < now) {
    const resetAt = now + RATE_LIMIT_WINDOW_MS;
    ipBuckets.set(ip, { hits: 1, resetAt });
    return { allowed: true, resetAt };
  }
  bucket.hits += 1;
  if (bucket.hits > RATE_LIMIT_MAX) {
    return { allowed: false, resetAt: bucket.resetAt };
  }
  return { allowed: true, resetAt: bucket.resetAt };
}

function applySecurityHeaders(response: NextResponse): NextResponse {
  response.headers.set("X-Frame-Options", "DENY");
  response.headers.set("X-Content-Type-Options", "nosniff");
  response.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  response.headers.set("Permissions-Policy", "camera=(), microphone=(), geolocation=()");
  if (process.env.NODE_ENV === "production") {
    response.headers.set(
      "Strict-Transport-Security",
      "max-age=31536000; includeSubDomains"
    );
  }
  return response;
}

export function middleware(request: NextRequest): NextResponse {
  const { pathname } = request.nextUrl;

  if (RATE_LIMIT_PATHS.test(pathname) && !RATE_LIMIT_EXEMPT.test(pathname)) {
    const ip = getClientIp(request);
    const result = checkRateLimit(ip);
    if (!result.allowed) {
      const res = NextResponse.json(
        { ok: false, error: "rate_limited" },
        {
          status: 429,
          headers: {
            "Retry-After": String(Math.max(1, Math.ceil((result.resetAt - Date.now()) / 1000))),
          },
        }
      );
      return applySecurityHeaders(res);
    }
  }

  if (APP_PATHS.test(pathname)) {
    if (process.env.E2E_BYPASS_AUTH !== "true") {
      const sessionCookie = getSessionCookie(request);
      if (!sessionCookie) {
        const url = request.nextUrl.clone();
        url.pathname = "/login";
        url.search = "";
        return applySecurityHeaders(NextResponse.redirect(url));
      }
    }
  }

  void SHARE_PATHS;
  void PUBLIC_API;

  return applySecurityHeaders(NextResponse.next());
}

export const config = {
  matcher: [
    "/home/:path*",
    "/settings/:path*",
    "/share/:path*",
    "/api/:path*",
  ],
};
