import { Resend } from "resend";

import { logger } from "@/lib/server/logger";

/**
 * Email sending helper. Wraps Resend with a graceful no-op fallback so:
 *   - Production builds with `RESEND_API_KEY` set → real send via Resend.
 *   - Dev / preview / test runs without the env → log "would send" + return ok.
 *   - Any send error → log + throw so callers can react (e.g. retry queue).
 *
 * Generated MVPs that need to send email (capabilities.emailNotifications === true) MUST use
 * this helper rather than instantiating `Resend` directly. Audits verify the import.
 *
 * `RESEND_FROM_EMAIL` env (e.g. "Acme <hello@acme.com>") is required in production. In dev the
 * fallback "ARIA MVP <onboarding@resend.dev>" works for Resend's sandbox testing.
 *
 * Do not edit this file.
 *
 * Example:
 *   await sendEmail({
 *     to: user.email,
 *     subject: "Your weekly digest",
 *     html: renderToStaticMarkup(<DigestEmail data={...} />),
 *   });
 */
export type SendEmailInput = {
  to: string | string[];
  subject: string;
  html: string;
  text?: string;
  from?: string;
  replyTo?: string;
};

export type SendEmailOutcome =
  | { ok: true; provider: "resend"; messageId: string | null }
  | { ok: true; provider: "noop"; messageId: null }
  | { ok: false; error: string };

let resendClient: Resend | null = null;

function getResendClient(): Resend | null {
  const apiKey = process.env.RESEND_API_KEY?.trim();
  if (!apiKey) return null;
  if (!resendClient) {
    resendClient = new Resend(apiKey);
  }
  return resendClient;
}

function getDefaultFrom(): string {
  const env = process.env.RESEND_FROM_EMAIL?.trim();
  if (env) return env;
  if (process.env.NODE_ENV === "production") {
    logger.warn("send_email_missing_from", {
      detail:
        "RESEND_FROM_EMAIL is not set in production. Using Resend onboarding sender; configure your verified sender on Vercel.",
    });
  }
  return "ARIA MVP <onboarding@resend.dev>";
}

export async function sendEmail(input: SendEmailInput): Promise<SendEmailOutcome> {
  const client = getResendClient();
  const from = input.from ?? getDefaultFrom();
  const to = Array.isArray(input.to) ? input.to : [input.to];

  if (!client) {
    logger.info("send_email_noop", {
      reason: "RESEND_API_KEY missing",
      to,
      subject: input.subject,
    });
    return { ok: true, provider: "noop", messageId: null };
  }

  try {
    const result = await client.emails.send({
      from,
      to,
      subject: input.subject,
      html: input.html,
      text: input.text,
      replyTo: input.replyTo,
    });
    if (result.error) {
      logger.error("send_email_resend_error", { error: result.error.message });
      return { ok: false, error: result.error.message };
    }
    return { ok: true, provider: "resend", messageId: result.data?.id ?? null };
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    logger.error("send_email_throw", { error: message });
    return { ok: false, error: message };
  }
}
