import {
  createCipheriv,
  createDecipheriv,
  randomBytes,
  scryptSync,
} from "node:crypto";

/**
 * Symmetric encryption helper for storing user-supplied secrets at rest (BYOK API keys, OAuth
 * refresh tokens, webhook signing secrets, etc.).
 *
 * Algorithm: AES-256-GCM with a 12-byte random IV per ciphertext. The output format is a single
 * base64 string with `iv | ciphertext | authTag` concatenated, so callers store one column.
 *
 * Key derivation:
 *   - Reads `SECRETS_ENCRYPTION_KEY` from env. ARIA's Vercel-provision step generates one (256-bit
 *     random hex) per project at deploy time and stores it on the Vercel project env.
 *   - In dev / when the env is missing, derives a key from a hardcoded salt + a warning log so
 *     local development still works (NEVER use the dev fallback in prod — middleware logs a loud
 *     warning if `NODE_ENV === "production"` and the env is missing).
 *
 * Generated MVPs MUST use these helpers (via `user-secret-store.ts`) rather than calling Node
 * crypto directly. The `audit-byok` audit rejects builds that store secrets without this helper.
 *
 * Do not edit this file.
 */

const ALGO = "aes-256-gcm";
const IV_LENGTH = 12;
const AUTH_TAG_LENGTH = 16;

let cachedKey: Buffer | null = null;

function getEncryptionKey(): Buffer {
  if (cachedKey) return cachedKey;
  const raw = process.env.SECRETS_ENCRYPTION_KEY?.trim();
  if (raw && raw.length >= 32) {
    // Accept either hex (64 chars), base64, or any string we can scrypt to 32 bytes.
    if (/^[0-9a-fA-F]{64}$/.test(raw)) {
      cachedKey = Buffer.from(raw, "hex");
    } else {
      cachedKey = scryptSync(raw, "aria-mvp-secrets-salt", 32);
    }
    return cachedKey;
  }
  if (process.env.NODE_ENV === "production") {
    console.error(
      "[encrypted-secret] SECRETS_ENCRYPTION_KEY is missing in production — using insecure fallback. Set the env var on the deployment to fix."
    );
  }
  cachedKey = scryptSync("aria-template-dev-encryption-fallback-key", "aria-mvp-secrets-salt", 32);
  return cachedKey;
}

/**
 * Encrypts a UTF-8 string. Returns a base64-encoded blob suitable for a `text` column in Postgres.
 */
export function encryptSecret(plaintext: string): string {
  if (typeof plaintext !== "string") {
    throw new TypeError("encryptSecret requires a string");
  }
  const iv = randomBytes(IV_LENGTH);
  const cipher = createCipheriv(ALGO, getEncryptionKey(), iv);
  const ct = Buffer.concat([cipher.update(plaintext, "utf8"), cipher.final()]);
  const tag = cipher.getAuthTag();
  return Buffer.concat([iv, ct, tag]).toString("base64");
}

/**
 * Decrypts a base64 blob produced by `encryptSecret`. Throws on tag mismatch (tampered ciphertext)
 * so callers can catch and treat as "secret unavailable" rather than returning bogus plaintext.
 */
export function decryptSecret(blob: string): string {
  if (typeof blob !== "string" || blob.length === 0) {
    throw new TypeError("decryptSecret requires a non-empty string");
  }
  const buf = Buffer.from(blob, "base64");
  if (buf.length < IV_LENGTH + AUTH_TAG_LENGTH + 1) {
    throw new Error("decryptSecret: ciphertext is too short");
  }
  const iv = buf.subarray(0, IV_LENGTH);
  const tag = buf.subarray(buf.length - AUTH_TAG_LENGTH);
  const ct = buf.subarray(IV_LENGTH, buf.length - AUTH_TAG_LENGTH);
  const decipher = createDecipheriv(ALGO, getEncryptionKey(), iv);
  decipher.setAuthTag(tag);
  const pt = Buffer.concat([decipher.update(ct), decipher.final()]);
  return pt.toString("utf8");
}
