import { getDbPool } from "@/lib/db";
import { decryptSecret, encryptSecret } from "@/lib/server/secrets/encrypted-secret";

/**
 * Per-user encrypted secret store. Backed by the `user_secrets` table (template migration 0004).
 *
 * Generated MVPs that need user-supplied API keys (BYOK) MUST use these helpers — never write
 * plaintext to the DB, never store keys in env vars per-user. The `audit-byok` audit verifies:
 *   - the AI/integration route reads via `getUserSecret(...)`,
 *   - the Settings tab writes via `setUserSecret(...)`,
 *   - no `process.env.<PROVIDER>_API_KEY` references in `src/features/**` for providers the spec
 *     lists in `capabilities.externalAi.provider` or `capabilities.externalApiIntegrations`.
 *
 * Conventions:
 *   - `provider_key` is a stable lowercase slug: `"openai"`, `"anthropic"`, `"firecrawl"`,
 *     `"serper"`, `"resend"`, `"github"`, etc. One slug per provider per user.
 *   - Updating an existing entry replaces the value (and bumps `updated_at`).
 *   - Reads return `null` when the user hasn't saved a key for that provider — caller must
 *     surface a friendly "configure API key in Settings" message rather than 500.
 *
 * Do not edit this file.
 */

export type UserSecretSummary = {
  providerKey: string;
  hasValue: true;
  /** Last 4 chars of the decrypted secret, for "•••• 1234"-style UI hints. */
  lastFour: string;
  updatedAt: Date;
};

/**
 * Returns the decrypted secret for `(userId, providerKey)`, or `null` if no row exists.
 * On decryption failure (key rotated, ciphertext tampered) returns `null` and logs.
 */
export async function getUserSecret(
  userId: string,
  providerKey: string
): Promise<string | null> {
  const pool = getDbPool();
  const r = await pool.query<{ ciphertext: string }>(
    "SELECT ciphertext FROM user_secrets WHERE user_id = $1 AND provider_key = $2 LIMIT 1",
    [userId, providerKey]
  );
  const row = r.rows[0];
  if (!row) return null;
  try {
    return decryptSecret(row.ciphertext);
  } catch (e) {
    console.warn("[user-secret-store] failed to decrypt secret", {
      userId,
      providerKey,
      error: e instanceof Error ? e.message : String(e),
    });
    return null;
  }
}

/**
 * Upserts (encrypts + stores) a secret for `(userId, providerKey)`. Trims the input — empty
 * strings are rejected with an error rather than silently writing a useless empty row.
 */
export async function setUserSecret(
  userId: string,
  providerKey: string,
  plaintext: string
): Promise<void> {
  const value = plaintext.trim();
  if (!value) {
    throw new Error("setUserSecret: refusing to store empty secret");
  }
  const ciphertext = encryptSecret(value);
  const pool = getDbPool();
  await pool.query(
    `INSERT INTO user_secrets (user_id, provider_key, ciphertext, created_at, updated_at)
     VALUES ($1, $2, $3, now(), now())
     ON CONFLICT (user_id, provider_key)
     DO UPDATE SET ciphertext = EXCLUDED.ciphertext, updated_at = now()`,
    [userId, providerKey, ciphertext]
  );
}

/**
 * Removes the stored secret for `(userId, providerKey)`. Idempotent.
 */
export async function deleteUserSecret(userId: string, providerKey: string): Promise<void> {
  const pool = getDbPool();
  await pool.query(
    "DELETE FROM user_secrets WHERE user_id = $1 AND provider_key = $2",
    [userId, providerKey]
  );
}

/**
 * Lists all stored providers for the user with redacted previews — safe to send to the client
 * for UI ("OpenAI: •••• 1234, last updated 2 days ago").
 */
export async function listUserSecrets(userId: string): Promise<UserSecretSummary[]> {
  const pool = getDbPool();
  const r = await pool.query<{
    provider_key: string;
    ciphertext: string;
    updated_at: Date;
  }>(
    "SELECT provider_key, ciphertext, updated_at FROM user_secrets WHERE user_id = $1 ORDER BY provider_key ASC",
    [userId]
  );
  const summaries: UserSecretSummary[] = [];
  for (const row of r.rows) {
    let lastFour = "";
    try {
      const v = decryptSecret(row.ciphertext);
      lastFour = v.length >= 4 ? v.slice(-4) : v;
    } catch {
      lastFour = "";
    }
    summaries.push({
      providerKey: row.provider_key,
      hasValue: true,
      lastFour,
      updatedAt: row.updated_at,
    });
  }
  return summaries;
}
