import { ReactNode } from "react";

import { HomeShell } from "@/components/app/home-shell";

/**
 * Wraps every route under `/home/**` in the `HomeShell` so the persistent header CTAs and
 * sub-nav from `src/config/home-nav.config.ts` follow the user across child pages (lists,
 * detail, create wizard, etc.).
 *
 * Hoisting from a per-page wrapper to a layout is intentional: it guarantees that a navigation
 * affordance the user sees on `/home` is still visible on `/home/foo/[id]` — without this,
 * users would lose their persistent "+ New X" button as soon as they clicked into anything.
 *
 * Do not edit this file. Extend nav by writing to `src/config/home-nav.config.ts`.
 */
export default function HomeSegmentLayout({ children }: { children: ReactNode }) {
  return <HomeShell>{children}</HomeShell>;
}
