"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { PropsWithChildren } from "react";

import { Button } from "@/components/ui/button";
import { homeNavConfig } from "@/config/home-nav.config";
import { pickActiveNavHref } from "@/lib/nav/is-active-nav-item";
import { cn } from "@/lib/utils";

/**
 * Stable shell for `/home/**`. Renders persistent header actions (create CTAs) and an optional
 * sub-nav rail above the page body. Both are driven by `src/config/home-nav.config.ts`, which
 * is the additive extension point ARIA codegen writes to during MVP build.
 *
 * **Do not edit this file** — it is on `mandatoryDoNotModifyPaths`. To add nav surfaces, write
 * to `home-nav.config.ts` instead.
 *
 * Behavioral guarantees:
 *   - Header actions render with the SAME visibility regardless of page state (empty/populated).
 *     Empty-state illustrations on a child page can re-render the same CTA at a larger size, but
 *     the header CTA is always present.
 *   - Sub-nav highlights the active route via `pickActiveNavHref` (longest-match-wins,
 *     boundary-aware) so a child route lights up exactly one tab — never both the
 *     section parent and its child.
 *   - The shell is fully optional: when both arrays are empty, only `children` renders — the
 *     bare template behaves identically to before.
 *   - **Defense in depth**: any nav entry whose `href` contains a `[bracket]` segment (e.g.
 *     `/home/boards/[id]/listings`) is silently dropped. The /home shell has no dynamic id in
 *     scope, so a literal `[id]` href would 404 at runtime (`useParams().id === "[id]"`). The
 *     ARIA spec schema, normalizer, and source audits already prevent this pre-deploy; this
 *     filter is the runtime safety net for already-shipped MVPs and any future regression.
 */

/** True iff `href` contains no Next.js dynamic-segment placeholders. */
function isStaticHref(href: string): boolean {
  return !/\[[^/\]]+\]/.test(href);
}

export function HomeShell({ children }: PropsWithChildren) {
  const pathname = usePathname() ?? "/home";

  const homeHeaderActions = homeNavConfig.homeHeaderActions.filter((a) => {
    if (!isStaticHref(a.href)) {
      if (process.env.NODE_ENV !== "production") {
        // eslint-disable-next-line no-console
        console.warn(
          `[home-shell] dropping homeHeaderAction with dynamic href: "${a.href}". ` +
            `Link to it from the parent detail page using a template literal instead.`,
        );
      }
      return false;
    }
    return true;
  });
  const homeSubNav = homeNavConfig.homeSubNav.filter((i) => {
    if (!isStaticHref(i.href)) {
      if (process.env.NODE_ENV !== "production") {
        // eslint-disable-next-line no-console
        console.warn(
          `[home-shell] dropping homeSubNav item with dynamic href: "${i.href}". ` +
            `Link to it from the parent detail page using a template literal instead.`,
        );
      }
      return false;
    }
    return true;
  });

  const hasHeader = homeHeaderActions.length > 0;
  const hasSubNav = homeSubNav.length > 0;
  const showShell = hasHeader || hasSubNav;
  const activeSubNavHref = pickActiveNavHref(
    pathname,
    homeSubNav.map((item) => item.href)
  );

  if (!showShell) {
    return <>{children}</>;
  }

  return (
    <div className="space-y-4">
      {hasHeader ? (
        <header
          className="flex flex-wrap items-center justify-end gap-2"
          aria-label="Home header actions"
        >
          {homeHeaderActions.map((action) => (
            <Button
              key={`${action.label}:${action.href}`}
              type="button"
              size="sm"
              render={<Link href={action.href} />}
            >
              {action.label}
            </Button>
          ))}
        </header>
      ) : null}

      {hasSubNav ? (
        <nav
          aria-label="Home sub-navigation"
          className="flex flex-wrap items-center gap-1 border-b text-sm"
        >
          {homeSubNav.map((item) => {
            const isActive = item.href === activeSubNavHref;
            return (
              <Link
                key={item.href}
                href={item.href}
                aria-current={isActive ? "page" : undefined}
                className={cn(
                  "-mb-px border-b-2 px-3 py-2 text-muted-foreground transition-colors hover:text-foreground",
                  isActive
                    ? "border-primary text-foreground"
                    : "border-transparent"
                )}
              >
                {item.label}
              </Link>
            );
          })}
        </nav>
      ) : null}

      <div>{children}</div>
    </div>
  );
}
