/**
 * Minimal structured logger used by all template-shipped server helpers.
 *
 * Behavior:
 *  - In production (`NODE_ENV === "production"`): one JSON line per call (parseable by Vercel
 *    log drains, Datadog, etc.).
 *  - In development: human-readable single line with the timestamp + level + message + payload.
 *
 * Generated MVPs SHOULD import from here instead of using `console.log` so that all server logs
 * have a consistent shape and can be filtered downstream.
 *
 * Do not edit this file.
 */
type LogLevel = "info" | "warn" | "error";

type LogPayload = Record<string, unknown>;

function emit(level: LogLevel, message: string, payload?: LogPayload): void {
  const entry = {
    ts: new Date().toISOString(),
    level,
    message,
    ...(payload ?? {}),
  };
  if (process.env.NODE_ENV === "production") {
    const fn = level === "error" ? console.error : level === "warn" ? console.warn : console.log;
    fn(JSON.stringify(entry));
    return;
  }
  const tail = payload ? ` ${JSON.stringify(payload)}` : "";
  const fn = level === "error" ? console.error : level === "warn" ? console.warn : console.log;
  fn(`[${entry.ts}] ${level.toUpperCase()} ${message}${tail}`);
}

export const logger = {
  info(message: string, payload?: LogPayload): void {
    emit("info", message, payload);
  },
  warn(message: string, payload?: LogPayload): void {
    emit("warn", message, payload);
  },
  error(message: string, payload?: LogPayload): void {
    emit("error", message, payload);
  },
};
