import { ReactNode } from "react";

import { SettingsShell } from "@/components/app/settings-shell";

/**
 * Wraps every route under `/settings/**` in `SettingsShell` so the header + tab strip stay
 * mounted as the user moves between settings tabs.
 *
 * Do not edit this file. Add new tabs by writing to `src/config/settings-tabs.config.ts` and
 * creating `src/app/(app)/settings/<slug>/page.tsx`.
 */
export default function SettingsSegmentLayout({ children }: { children: ReactNode }) {
  return <SettingsShell>{children}</SettingsShell>;
}
