"use client";

import { useEffect } from "react";

/**
 * Catastrophic root error boundary — used when the root layout itself throws (e.g. a fonts /
 * provider crash). Must include `<html>` and `<body>` because it replaces the root document.
 *
 * Do not edit this file.
 */
export default function GlobalError({
  error,
}: {
  error: Error & { digest?: string };
  reset: () => void;
}) {
  useEffect(() => {
    console.error("[global-error]", error);
  }, [error]);

  return (
    <html>
      <body
        style={{
          margin: 0,
          minHeight: "100vh",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontFamily:
            "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
          background: "#0a0a0a",
          color: "#fafafa",
        }}
      >
        <div style={{ textAlign: "center", padding: "2rem", maxWidth: 480 }}>
          <h1 style={{ fontSize: "1.5rem", fontWeight: 600, marginBottom: "0.5rem" }}>
            Application error
          </h1>
          <p style={{ fontSize: "0.875rem", opacity: 0.7, marginBottom: "1rem" }}>
            The app failed to render. Please try reloading the page.
          </p>
          {error.digest ? (
            <p style={{ fontSize: "0.75rem", opacity: 0.5 }}>Reference: {error.digest}</p>
          ) : null}
          <button
            type="button"
            onClick={() => {
              window.location.assign("/");
            }}
            style={{
              display: "inline-block",
              marginTop: "1rem",
              padding: "0.5rem 1rem",
              background: "#fafafa",
              color: "#0a0a0a",
              border: "none",
              borderRadius: "0.375rem",
              textDecoration: "none",
              fontSize: "0.875rem",
              cursor: "pointer",
              fontFamily: "inherit",
            }}
          >
            Reload
          </button>
        </div>
      </body>
    </html>
  );
}
