/**
 * Typed error class thrown by `requireSession`, `parseJsonBody`,
 * etc. The `withApiErrorHandling` wrapper translates these into the standard `errJson` envelope.
 *
 * Throw, don't return — handler code stays readable when each precondition can short-circuit
 * with `throw new ApiError(...)`.
 *
 * Do not edit this file.
 */
export class ApiError extends Error {
  readonly name = "ApiError";

  constructor(
    readonly code: string,
    readonly status: number,
    readonly detail?: string
  ) {
    super(`${code} (${String(status)})${detail ? `: ${detail}` : ""}`);
  }
}

export function isApiError(value: unknown): value is ApiError {
  return value instanceof ApiError;
}
