import { NextResponse } from "next/server";

/**
 * Single response envelope for every API route in this MVP.
 *
 * Generated MVPs MUST use these helpers instead of constructing `NextResponse.json` directly,
 * so client code (and the runtime smoke test) can rely on a stable `{ ok, data, error, detail }`
 * shape for every route. Audits will fail builds that bypass these helpers.
 *
 * Do not edit this file.
 *
 * Examples:
 *   return okJson({ users: [...] });
 *   return errJson("not_found", 404);
 *   return errJson("invalid_payload", 400, "field 'email' is required");
 */

export type ApiOk<T> = { ok: true; data: T };
export type ApiErr = { ok: false; error: string; detail?: string };
export type ApiResponse<T> = ApiOk<T> | ApiErr;

export function okJson<T>(data: T, init?: ResponseInit): NextResponse<ApiOk<T>> {
  return NextResponse.json({ ok: true, data }, init);
}

export function errJson(
  error: string,
  status = 400,
  detail?: string
): NextResponse<ApiErr> {
  return NextResponse.json({ ok: false, error, detail }, { status });
}
