import type { ZodType } from "zod";

import { ApiError } from "./api-error";

/**
 * Parses and validates the JSON body of an incoming `Request` against a Zod schema. Throws
 * `ApiError("invalid_payload", 400, <flattened message>)` on parse failure.
 *
 * Generated MVP POST/PATCH/PUT routes MUST use this — the `audit-input-validation` audit fails
 * the build when a write handler does not validate its input.
 *
 * Do not edit this file.
 *
 * Example:
 *   const schema = z.object({ title: z.string().min(1).max(120) });
 *   const body = await parseJsonBody(req, schema);
 *   await db.insert("checklists", { ...body, user_id });
 */
export async function parseJsonBody<T>(req: Request, schema: ZodType<T>): Promise<T> {
  let raw: unknown;
  try {
    raw = await req.json();
  } catch {
    throw new ApiError("invalid_payload", 400, "request body is not valid JSON");
  }
  const parsed = schema.safeParse(raw);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .slice(0, 4)
      .map((i) => `${i.path.join(".") || "<root>"}: ${i.message}`)
      .join("; ");
    throw new ApiError("invalid_payload", 400, issues);
  }
  return parsed.data;
}
