import { headers } from "next/headers";

import { auth } from "@/lib/auth";

import { ApiError } from "./api-error";

/**
 * Extracts the authenticated session for an API route. Throws `ApiError("unauthorized", 401)`
 * when no session is present.
 *
 * Generated MVP API routes MUST call this at the top of any handler that accesses user data —
 * the `audit-auth-gating` source audit fails the build for routes that touch user data without it.
 *
 * Do not edit this file.
 *
 * Example:
 *   export async function POST(req: Request) {
 *     const session = await requireSession();
 *     // ... use session.user.id
 *   }
 */
export async function requireSession(): Promise<{
  user: { id: string; email: string | null; name: string | null };
  sessionId: string;
}> {
  const sess = await auth.api.getSession({ headers: await headers() });
  if (!sess?.user?.id) {
    throw new ApiError("unauthorized", 401);
  }
  return {
    user: {
      id: sess.user.id,
      email: sess.user.email ?? null,
      name: sess.user.name ?? null,
    },
    sessionId: sess.session?.id ?? "",
  };
}
