import type { NextResponse } from "next/server";

import { logger } from "@/lib/server/logger";

import { isApiError } from "./api-error";
import { errJson } from "./json-response";

/**
 * Wraps an App Router handler so that:
 *   - Any thrown `ApiError` becomes the standard `errJson` envelope with the right HTTP status.
 *   - Any other thrown error is logged with stack + becomes `errJson("internal_error", 500)`.
 *   - Successful responses pass through unchanged.
 *
 * Generated MVP API routes are encouraged (but not required) to wrap their handlers with this
 * helper so they don't have to write try/catch boilerplate. The `audit-api-envelope` audit
 * accepts both wrapped (uses this helper) and unwrapped (calls okJson/errJson directly) routes.
 *
 * Do not edit this file.
 *
 * Example:
 *   export const POST = withApiErrorHandling(async (req) => {
 *     const session = await requireSession();
 *     const body = await parseJsonBody(req, mySchema);
 *     return okJson({ created: true });
 *   });
 */
type Handler<C> = (
  req: Request,
  ctx: C
) => Promise<NextResponse> | NextResponse;

export function withApiErrorHandling<C = unknown>(handler: Handler<C>): Handler<C> {
  return async (req, ctx) => {
    try {
      return await handler(req, ctx);
    } catch (e) {
      if (isApiError(e)) {
        return errJson(e.code, e.status, e.detail);
      }
      const message = e instanceof Error ? e.message : String(e);
      const stack = e instanceof Error ? e.stack : undefined;
      logger.error("api_handler_unhandled_error", {
        url: req.url,
        method: req.method,
        message,
        stack,
      });
      return errJson("internal_error", 500);
    }
  };
}
