/**
 * SQL schema conventions used by ARIA-generated consumer MVPs.
 *
 * Generated migrations (numbered >= 0005) MUST follow these rules:
 *
 *   1. Table names:
 *      - snake_case ASCII (`workouts`, `daily_logs`, `team_members`)
 *      - plural nouns
 *      - Reserved by template — DO NOT create these in your migrations:
 *          user, session, account, verification,
 *          user_secrets, app_events, rate_limits
 *
 *   2. Every table that holds per-user data MUST have:
 *        "user_id" text NOT NULL REFERENCES "user"("id") ON DELETE CASCADE,
 *      with an index on user_id (most reads filter by it).
 *
 *   3. Every table SHOULD have:
 *        "id" text NOT NULL DEFAULT gen_random_uuid()::text PRIMARY KEY,
 *        "created_at" timestamptz NOT NULL DEFAULT now(),
 *        "updated_at" timestamptz NOT NULL DEFAULT now()
 *
 *   4. Use `IF NOT EXISTS` everywhere so re-runs are idempotent.
 *
 *   5. Numeric-but-money values: prefer `bigint` storing minor units (cents) over `numeric`.
 *
 *   6. Booleans always have explicit DEFAULT.
 *
 * Do not edit this file.
 */

export const RESERVED_TABLE_NAMES: ReadonlySet<string> = new Set([
  "user",
  "session",
  "account",
  "verification",
  "user_secrets",
  "app_events",
  "rate_limits",
]);

export const TEMPLATE_BASELINE_MIGRATION_NUMBERS: ReadonlySet<number> = new Set([
  1, 2, 3, 4,
]);

/** Template-owned migrations end at 0004; product schema starts at 0005. */
export const FIRST_GENERATED_MIGRATION_NUMBER = 5;

/**
 * Returns true if the given file basename (e.g. "0005_workouts.sql") is a valid
 * generated-MVP migration filename: `NNNN_snake_case.sql` with NNNN >= 0005.
 */
export function isValidGeneratedMigrationFilename(basename: string): boolean {
  const m = /^(\d{4})_[a-z0-9_]+\.sql$/.exec(basename);
  if (!m) return false;
  const n = parseInt(m[1]!, 10);
  return n >= FIRST_GENERATED_MIGRATION_NUMBER;
}
